// Generated by the WOLips Templateengine Plug-in at Apr 14, 2015 4:13:55 PM
package your.app;

import com.webobjects.foundation.NSLog;

import com.webobjects.appserver.WOApplication;

public class Application extends WOApplication {
	public static void main(String[] argv) {
		WOApplication.main(argv, Application.class);
	}

	public Application() {
		NSLog.out.appendln("Welcome to " + name() + "!");
		/* ** put your initialization code in here ** */
		setAllowsConcurrentRequestHandling(true);
	}
}
