// Generated by the WOLips Templateengine Plug-in at Apr 14, 2015 4:13:55 PM
package your.app;

import com.webobjects.appserver.WOSession;

public class Session extends WOSession {
	private static final long serialVersionUID = 1L;

	public Session() {
	}
}
