// Generated by the WOLips Templateengine Plug-in at Apr 24, 2015 6:04:56 PM
package your.app;

import com.webobjects.appserver.WOSession;

public class Session extends WOSession {
	private static final long serialVersionUID = 1L;

	public Session() {
	}
}
